### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by boltadvantage** [lnbits/lnbits-bitcoin-onchain-and-lightning-payment-gateway#2] opened 2022-07-19 12:02 UTC
I've installed the plugin and did a test transaction.

The invoice loads just fine, and I've paid it with another wallet. The transaction has gone through but when the invoice polls the server to check for payment I'm getting a 500 error.

Below appears to the error I'm receiving.

(psycopg2.ProgrammingError) can't adapt type 'Header' [SQL: SELECT *, COALESCE((SELECT balance FROM balances WHERE wallet = wallets.id), 0) AS balance_msat FROM wallets WHERE adminkey = %s OR inkey = %s ] [parameters: (Header(None), Header(None))] (Background on this error at: http://sqlalche.me/e/13/f405)

So the payment shows in the wallet but the invoice never completes on the screen.

**Comment by boltadvantage** [comment] 2022-07-19 12:11
Here is the log. 

`bundle.js:638 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'onInvoicePaid')"

(found in <Root>)
warn @ bundle.js:638
logError @ bundle.js:1897
globalHandleError @ bundle.js:1892
handleError @ bundle.js:1852
invokeWithErrorHandling @ bundle.js:1875
callHook @ bundle.js:4224
Vue._init @ bundle.js:5006
Vue @ bundle.js:5082
(anonymous) @ CHARGE ID:427
bundle.js:1901 TypeError: Cannot read properties of undefined (reading 'onInvoicePaid')
    at Vue.startPaymentNotifier (CHARGE ID:452:44)
    at Vue.created (CHARGE ID:534:12)
    at invokeWithErrorHandling (bundle.js:1867:59)
    at callHook (bundle.js:4224:9)
    at Vue._init (bundle.js:5006:7)
    at new Vue (bundle.js:5082:10)
    at CHARGE ID:427:3
    	
logError @ bundle.js:1901
globalHandleError @ bundle.js:1892
handleError @ bundle.js:1852
invokeWithErrorHandling @ bundle.js:1875
callHook @ bundle.js:4224
Vue._init @ bundle.js:5006
Vue @ bundle.js:5082
(anonymous) @ CHARGE ID:427`

**Comment by blackcoffeexbt** [comment] 2022-07-19 12:33
@jeremycady Where you using the legend.lnbits.com instance of lnbits or your own instance? If your own instance, do you know which commit you were running?

**Comment by boltadvantage** [comment] 2022-07-19 12:38
I'm using Voltage App for my instance. Looks like the commit version is: v0.1.1_e7dd3ec

I should have checked that as well. I see that they are behind on the Thunderhub version as well.

**Comment by blackcoffeexbt** [comment] 2022-07-19 12:39
Yes, I've seen the same issue with my own instance of Voltage. I'll test on the `main` branch but I think that this is a bug in lnbits that has been fixed.

**Comment by boltadvantage** [comment] 2022-07-19 12:42
Understood. I may reach out to Voltage then. My apologies for using up some of your bandwidth.

**Comment by blackcoffeexbt** [comment] 2022-07-19 12:44
No worries @jeremycady Thanks for being thoughtful enough to raise the issue :)

**Comment by blackcoffeexbt** [comment] 2022-07-19 15:33
For the sake of sanity, I've spun up my own instance of LNbits / main and the plugin is working fine. The issue is almost certainly on Voltage's side.

**Comment by boltadvantage** [comment] 2022-07-19 15:50
I started looking into what is needed to run it on a different server and then maybe point it to the Voltage Node.

May even look at running it on my local node if I can the url to point through Cloudflare. I noticed they just updated their service so I'll have to review their changes.

**Comment by satoshidave** [comment] 2022-10-02 15:49
Hi! I'm too getting error 500 when user pay. Im using legend.lnbits.com instance

Browser console shows:

`quasar.umd.js:2045          GET https://legend.lnbits.com/satspay/api/v1/charge/balance/_my_charge_payment_id_variable 500`

Also, executing GET https://legend.lnbits.com/satspay/api/v1/charge/balance/ endpoint from swagger documentation, and from Postman, Im getting error 500: Internal Server Error

Maybe if this error solvers, the plugins works successful

**Comment by blackcoffeexbt** [comment] 2022-10-02 16:20
@satoshidave thanks for raising this issue. I'll take a look into this tomorrow.

**Comment by satoshidave** [comment] 2022-10-10 21:19
Hi guys! I found the issue.
This plugin works perfect on production. The issue is when this is running on localhost.
In lnbits_api.php, line 28, I replaced the get_site_url() function by my domain. Also works removing all line 28.

Again, in production works perfect without edit.
Best regards for blackcoffee, community and all the LNbits team <3

**Comment by blackcoffeexbt** [comment] 2022-10-10 21:22
Excellent! Thanks for letting us know @satoshidave I'll close this issue. :)

**Closed as completed by blackcoffeexbt** 2022-10-10 21:22 UTC
